# Generated by Django 4.1.3 on 2023-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailerlink',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodeperseason',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
