# Generated by Django 4.1.3 on 2023-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anime_trailerlink_alter_anime_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodeperseason',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='trailerlink',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', upload_to=''),
        ),
    ]
