# Generated by Django 4.1.3 on 2023-11-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_anime_banner_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
        migrations.AddField(
            model_name='anime',
            name='endyear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='startyear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
