# Generated by Django 4.1.3 on 2023-11-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_anime_year_anime_endyear_anime_startyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchedstatus',
            name='viewed',
            field=models.BooleanField(),
        ),
    ]
