# Generated by Django 4.1.3 on 2023-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userwatchedstatus_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchedstatus',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
